### ISSUE TITLE
Support GitHub Enterprise service connection type

### ISSUE THREAD

**Issue by sarah-m95** [NuKeeperDotNet/NuKeeper-AzureDevops-extension#51]
I am trying to run the Nukeeper extension against an instance of GitHub Enterprise. However, when I set the gitHubConnection parameter to consume my GitHub Enterprise service connection, I'm told the plug-in doesn't support GitHub Enterprise connections. Would it be possible to add that as a feature? For clarity, "GitHub Enterprise" is the name of my service connection in DevOps.

My YAML:
```
    - task: NuKeeper@0
      inputs:
        arguments: '--api=https://github.carmax.com/api/v3 --change minor --consolidate --maxpackageupdates 5 --fork SingleRepositoryOnly --include ".*" --exclude "!.*" --verbosity Detailed'
        targetFolder: 'src'
        version: '0.*'
        gitHubConnection: 'GitHub Enterprise'
```

The error message:
![nukeeper bug](https://user-images.githubusercontent.com/60396960/75820813-0d0c1180-5d6b-11ea-8cd8-18e21eb23e4f.PNG)
